apply plugin: 'java'

[compileJava, compileTestJava, javadoc]*.options*.encoding = 'UTF-8'

//version rootProject.ext.VERSION_NAME
//group rootProject.ext.GROUP

ext {
    // artifactId
    aarId = "AndResGuard-cli"
    // snapshot version use x.x.x-snapshot, release version use x.x.x
    versionName = rootProject.ext.versionName
    // 默认 false, true 代表推远程maven仓
    publishToServer = rootProject.ext.publishToServer
    groupID = rootProject.ext.groupID
    // aar local path
    localPath = '../repo'
}

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  //implementation group: 'com.tencent.mm', name: 'AndResGuard-core', version: version
  implementation project(':AndResGuard-core')
}

sourceSets {
  main {
    java {
      srcDir 'src'
    }
  }
}

jar {
  manifest {
    attributes 'Main-Class': 'com.tencent.mm.resourceproguard.cli.CliMain'
    attributes 'Manifest-Version': '1.0'
    attributes "Jar-Version": versionName
    attributes "Build-Time": releaseTime()
  }
  from {
    configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
  }
}

// copy the jar to work directory
task buildJar(type: Copy, dependsOn: [build, jar]) {
  from('build/libs') {
    include '*' + version + '*.jar'
  }
  into('../tool_output')
}

def releaseTime() {
  return new Date().format("yyyy-MM-dd HH:mm ZZZ", TimeZone.getDefault())
}

defaultTasks 'buildJar'

apply from: rootProject.file('gradle/java-artifacts.gradle')
